config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :categories do
    resources :payments
  end
end
  # Defines the root path route ("/")
  # root "articles#index"

  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, User
    return unless user.present?

    can :read, Category
    can :manage, Category, user_id: user.id
    can :read, Payment
    can :manage, Payment, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_payments
  has_many :payments, through: :category_payments
  validates :name, :icon, presence: true
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :category_payments
  has_many :categories, through: :category_payments
  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :payments, foreign_key: 'author_id'
  has_many :categories
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index]
  before_action :update_allowed_parameters, if: :devise_controller?
  load_and_authorize_resource unless: :devise_controller?

  def after_sign_in_path_for(resource)
    resource.categories
    user_categories_path(user_id: current_user.id)
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user = current_user
    @categories = @user.categories
  end

  def new
    @user = current_user
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.new(category_params)
    if @category.save
      redirect_to user_categories_path(@user), notice: 'Category created successfully!'
    else
      puts @category.errors.full_messages
      render :new
    end
  end

  def show; end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @user = current_user
    @category = Category.find(params[:category_id])
    @payments = @category.payments.where(author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @user = current_user
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  def create
    @user = current_user
    @category = Category.find(params[:category_id])
    @payment = @user.payments.new(payment_params)
    @payment.author = current_user

    if @payment.save
      @categorypayment = CategoryPayment.create(category: @category, payment: @payment)
      redirect_to user_category_payments_path(@category), notice: 'Transaction created successfully!'
    else
      puts @payment.errors.full_messages
      render :new
    end
  end

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/categories/index.html.erb
<nav>
  <ul id="nav">
  <li><%= link_to "Back", users_path, class: "back" %></li>
  </ul>
  <h1 class ="login"> Categories</h1>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "logout"  %>
</nav>

<% @categories.each do |category| %>
  <%@total_amount = category.payments.sum(:amount)%>
  <div class ="card"> 
  <%= link_to user_category_payments_path(user_id: @user.id, category_id:  category.id) do  %>
    <div class ="category-card">  
<img src="<%= category.icon %>" alt="User" class="picture" />
<div class="category-content">
<h2><%=category.name%></h2>
<h2><%=category.created_at.strftime("%d-%m-%Y")%></h2>
</div>
<div class="amt">
<h2>$<%=@total_amount%></h2>
</div>
</div>
<%end%>
</div>
<%end%>
<div class ="new-item">
<%= link_to "New Category", new_user_category_path(user_id: @user.id), class:"new-category" %>
</div>

app/views/categories/new.html.erb
<nav>
  <ul id="nav">
  <li><%= link_to "Back", user_categories_path, class: "back" %></li>
  </ul>
  <h1 class ="login"> Categories</h1>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "logout"  %>
</nav>
<div class ="login-content">
<%= form_with(model: @category, url: user_categories_path) do |form| %>
      <%= form.text_field :name, placeholder: 'Name', class: "input"  %>
      <%= form.text_field :icon, placeholder: 'Icon',  class: "input"  %>
      <%= form.submit 'Submit', class: "form-btn" %>
      </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body> 
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<nav>
  <ul id="nav">
  <li><%= link_to "Back", user_categories_path, class: "back" %></li>
  </ul>
  <h1 class ="login"> Transaction</h1>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "logout"  %>
</nav>
<div class="payment">
<h2><%= @category.name %></h2>
<h2>$<%=@payments.sum(:amount)%></h2>
</div>
<% @payments.each do |payment| %>
    <div class ="card-payment"> 
  <h2><%= payment.name %></h2>
  <p>$<%= payment.amount %></p>
  </div>
<% end %>
<div class ="new-item">
<%= link_to "New Transaction", new_user_category_payment_path(user_id: @user.id, category_id: @category.id), class: "new-category" %>
</div>

app/views/payments/new.html.erb
<nav>
  <ul id="nav">
  <li><%= link_to "Back", user_category_payments_path(user_id: @user.id, category_id: @category.id), class: "back" %></li>
  </ul>
  <h1 class ="login"> Transaction</h1>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "logout"  %>
</nav>
    <div class ="login-content">
    <%= form_with(model: @payment, url: user_category_payments_path) do |form| %>
          <%= form.text_field :name, placeholder: 'Name', class: "input"  %>
          <%= form.text_field :amount, placeholder: 'Amount',  class: "input"  %>
          <%= form.submit 'Submit', class: "form-btn" %>
          </div>
  <% end %>

app/views/users/index.html.erb
<nav>
  <button id="hamburger-btn">&#9776;</button>
  <ul id="menu">
  <li>About</li>
    <li><%= link_to "Login", new_user_session_path %></li>
    <li><%= link_to "Sign up",  new_user_registration_path %></li>
  </ul>
  <h1 class ="header"> Home</h1>
</nav>
<div class = "content">
<div class ="budget">
<h2>BudgetIT App</h2>
</div>
</div>
<div class ="new-item">
<%= link_to "Login",  new_user_session_path, class:"new-category" %>
</div>
<%= link_to "Sign up",  new_user_registration_path, class: "signup" %>